Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -16,44 +16,42 @@ on:
 
 jobs:
   build:
-
     runs-on: self-hosted
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-    - name: Build with Maven
-      env:
-        DB_URL: ${{ secrets.DB_URL }}
-        DB_USERNAME: ${{ secrets.DB_USERNAME }}
-        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-      run: mvn -B package --file pom.xml
-    - name: Execute Jar File
-      env:
-        DB_URL: ${{ secrets.DB_URL }}
-        DB_USERNAME: ${{ secrets.DB_USERNAME }}
-        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-      run: |
-        # Kill any processes on port 80
-        process_id=$(sudo lsof -t -i:80)
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: maven
+      - name: Build with Maven
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+        run: mvn -B package --file pom.xml
+      - name: Execute Jar File
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+        run: |
+          process_id=$(sudo lsof -t -i:80) || { echo "lsof command failed"; exit 1; }
 
-        if [ -n "$process_id" ]; then
-          sudo kill -9 "$process_id"
-        else
-          echo "No processes found on port 80."
-        fi
+          if [ -n "$process_id" ]; then
+            sudo kill -9 "$process_id" || { echo "Failed to kill process $process_id"; exit 1; }
+          else
+            echo "No processes found on port 80."
+          fi
 
-        # Start the application
-        sudo java -jar /home/ubuntu/actions-runner/_work/transit-onu-gnec-hackathon-backend/transit-onu-gnec-hackathon-backend/target/transit-onu-gnec-hackaton-backend-0.0.1-SNAPSHOT.jar &
-        # Check if the app is responding on localhost:8080 
-        sleep 30
-        if curl -I http://localhost:8080; then
-          echo "Application is reachable."
-        else
-          echo "Application did not start or is not reachable."
-        fi
+          # Start the application
+          sudo java -jar /home/ubuntu/actions-runner/_work/transit-onu-gnec-hackathon-backend/transit-onu-gnec-hackathon-backend/target/transit-onu-gnec-hackaton-backend-0.0.1-SNAPSHOT.jar &
+          # Check if the app is responding on localhost:8080 
+          sleep 30
+          if curl -I http://localhost:8080; then
+            echo "Application is reachable."
+          else
+            echo "Application did not start or is not reachable."
+          fi
